name: gpa_calculator
description: "GPA Calculator - Backend Integrated"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  shared_preferences: ^2.5.3
  connectivity_plus: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon.png"
  min_sdk_size: 21

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: BauhausStd
      fonts:
        - asset: fonts/BauhausStd-Medium.otf
